-- Durable, user-scoped interview runtime. Session ids are generated by the application
-- so the schema does not depend on optional PostgreSQL UUID extensions.
CREATE TABLE interview_sessions (
  id VARCHAR(36) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  target_role TEXT NOT NULL DEFAULT '',
  topic TEXT NOT NULL,
  status VARCHAR(16) NOT NULL, -- IN_PROGRESS / COMPLETED / CANCELLED / FAILED
  current_question_sequence INT NOT NULL,
  main_question_count INT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);
CREATE INDEX idx_interview_sessions_user_status_created
  ON interview_sessions(user_id, status, created_at DESC);

CREATE TABLE interview_questions (
  id BIGSERIAL PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
  sequence INT NOT NULL,
  kind VARCHAR(16) NOT NULL, -- MAIN / FOLLOW_UP
  prompt TEXT NOT NULL,
  answer TEXT,
  score SMALLINT,
  answer_request_id VARCHAR(80),
  response_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  answered_at TIMESTAMPTZ,
  UNIQUE(session_id, sequence),
  UNIQUE(session_id, answer_request_id),
  CHECK (score IS NULL OR score BETWEEN 0 AND 10)
);
CREATE INDEX idx_interview_questions_session_sequence
  ON interview_questions(session_id, sequence);
